# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 678bcd2e3a34557b3bfc8bba7e5a91fc1446887e6d6036ef71fd84ef02747766f37300fccc1121b812015bf47b9181072bcf7692a142079d68b30d84c8391eca

test:
  secret_key_base: 570b96873ba1d6867522113fd42a1f570cd1723c4fab6d245eca80d611a489d032e766473d9cf8bceb5396de62407095c48b4c2f146d48ab49487ed892ea9d60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
