class CreateClaims < ActiveRecord::Migration[5.0]
  def change
    create_table :claims do |t|
      t.integer :doctor_id
      t.integer :patient_id
      t.string :claim_type
      t.string :civil_status
      t.string :attention_cause
      t.string :patient_name
      t.string :doctor_name
      t.integer :age
      t.string :gender
      t.string :clinical_summary
      t.boolean :referral_yn
      t.string :referral_doctor
      t.string :referral_specialty
      t.integer :referral_phone
      t.string :symptoms
      t.date :first_symptoms_date
      t.date :first_consultation_date
      t.string :disease_type
      t.boolean :relation_other_disease_yn
      t.string :relation_other_disease
      t.string :evolution
      t.string :disease_cause
      t.boolean :origin_primary_yn
      t.string :origin_primary_type
      t.string :lab_tests
      t.integer :waiste_size
      t.integer :weight
      t.integer :pressure
      t.string :physical_exploration_details
      t.string :lab_studies_results
      t.string :form_accountable_name
      t.string :form_accountable_address
      t.string :purpose
      t.string :data_signature
      t.string :cie_10
      t.string :definite_diagnose
      t.date :diagnose_date
      t.string :cpt_4
      t.date :tx_start
      t.string :medicine_name
      t.integer :medicine_dose
      t.integer :medicine_duration_number
      t.string :medicine_duration_type
      t.string :tx_other_name
      t.string :tx_other_justification
      t.integer :tx_other_days
      t.integer :tx_other_sessions
      t.string :chemo_type
      t.integer :chemo_sessions
      t.string :chemo_dose
      t.string :chemo_intervals
      t.integer :physical_rehab_days
      t.integer :physical_rehab_sessions
      t.integer :nursing_days
      t.integer :nursing_hpd
      t.boolean :nursing_morning
      t.boolean :nursing_evening
      t.boolean :nursing_night
      t.boolean :nursing_24
      t.string :tx_observations
      t.string :technique_description
      t.boolean :special_equipment_yn
      t.string :special_equipment_detail
      t.boolean :procedure_mat_yn
      t.string :procedure_mat_detail
      t.boolean :procedure_mat_complications_yn
      t.string :procedure_mat_complications_describe
      t.string :list_other_doctors
      t.integer :claim_staff_id
      t.string :inter_consultation_name
      t.string :inter_consultation_specialty
      t.boolean :inter_consultation_network_yn
      t.string :inter_consultation_dates
      t.string :inter_consultation_description
      t.boolean :other_tx_other_doctor_yn
      t.string :other_tx_other_doctor_name
      t.string :other_tx_other_doctor_specialty
      t.string :patient_current_status
      t.boolean :tx_continues_yn
      t.string :tx_continues_type
      t.string :tx_continues_duration
      t.string :tx_continues_doctors
      t.string :accident_description
      t.date :discharge_date
      t.string :hospital_name
      t.string :hospital_city
      t.string :hospital_stay_type
      t.string :surgery_performed
      t.string :findings
      t.date :hospital_admission_date
      t.date :surgery_admission_date
      t.string :hospital_discharge_date
      t.boolean :disability_caused_yn
      t.string :disability_caused_type
      t.date :disability_caused_from
      t.date :disability_caused_until
      t.boolean :biopsy_yn
      t.string :doctor_specialty
      t.string :doctor_address
      t.string :doctor_cedula_pro
      t.string :doctor_cedula_esp
      t.string :doctor_rfc
      t.integer :doctor_phone
      t.string :doctor_email
      t.string :doctor_supplier_number
      t.integer :budget_surgeon
      t.integer :budget_assistants
      t.integer :budget_anesthesiologist
      t.string :hospital_surgery_name
      t.string :hospital_entity
      t.date :sugery_date
      t.string :doctor_signature
      t.string :doctor_signature_place
      t.date :doctor_signature_date
      t.boolean :agreement_ins_yn
      t.string :identification_file
      t.integer :health_summary_id
      t.string :insurance_name
      t.integer :insurance_id
      t.string :tx_descritption
      t.string :medicine_quantity

      t.timestamps

    end
  end
end
